// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/recipe/request.proto

package erpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request schema for calling Store on recipe.
type RecipeStoreRequest struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecipeStoreRequest) Reset()         { *m = RecipeStoreRequest{} }
func (m *RecipeStoreRequest) String() string { return proto.CompactTextString(m) }
func (*RecipeStoreRequest) ProtoMessage()    {}
func (*RecipeStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f846b28d7894a8a4, []int{0}
}

func (m *RecipeStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeStoreRequest.Unmarshal(m, b)
}
func (m *RecipeStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeStoreRequest.Marshal(b, m, deterministic)
}
func (m *RecipeStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeStoreRequest.Merge(m, src)
}
func (m *RecipeStoreRequest) XXX_Size() int {
	return xxx_messageInfo_RecipeStoreRequest.Size(m)
}
func (m *RecipeStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeStoreRequest proto.InternalMessageInfo

func (m *RecipeStoreRequest) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func init() {
	proto.RegisterType((*RecipeStoreRequest)(nil), "edible.recipe.request.RecipeStoreRequest")
}

func init() { proto.RegisterFile("protos/edible/recipe/request.proto", fileDescriptor_f846b28d7894a8a4) }

var fileDescriptor_f846b28d7894a8a4 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0x2f, 0x4a, 0x4d, 0xce, 0x2c, 0x00,
	0x51, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x7a, 0x60, 0x49, 0x21, 0x51, 0x88, 0xa4, 0x1e, 0x44, 0x52,
	0x0f, 0x2a, 0x29, 0xa5, 0x80, 0x55, 0x6b, 0x6e, 0x7e, 0x4a, 0x6a, 0x0e, 0x44, 0xa3, 0x92, 0x37,
	0x97, 0x50, 0x10, 0x58, 0x34, 0xb8, 0x24, 0xbf, 0x28, 0x35, 0x08, 0xa2, 0x4f, 0xc8, 0x94, 0x8b,
	0x1d, 0xa2, 0xb6, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x5a, 0x0f, 0xd5, 0x02, 0x88,
	0x11, 0x10, 0x9d, 0x41, 0x30, 0xb5, 0x4e, 0x6c, 0x51, 0x2c, 0xa9, 0x45, 0x05, 0x49, 0x49, 0x6c,
	0x60, 0xb3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x98, 0x5b, 0xf7, 0xba, 0x00, 0x00,
	0x00,
}
