// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/recipe/response.proto

package erpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The response you get for calling Store on recipe.
type RecipeStoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeStoreResponse) Reset()         { *m = RecipeStoreResponse{} }
func (m *RecipeStoreResponse) String() string { return proto.CompactTextString(m) }
func (*RecipeStoreResponse) ProtoMessage()    {}
func (*RecipeStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d319aa5d297fd1ed, []int{0}
}

func (m *RecipeStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeStoreResponse.Unmarshal(m, b)
}
func (m *RecipeStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeStoreResponse.Marshal(b, m, deterministic)
}
func (m *RecipeStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeStoreResponse.Merge(m, src)
}
func (m *RecipeStoreResponse) XXX_Size() int {
	return xxx_messageInfo_RecipeStoreResponse.Size(m)
}
func (m *RecipeStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeStoreResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RecipeStoreResponse)(nil), "edible.recipe.response.RecipeStoreResponse")
}

func init() {
	proto.RegisterFile("protos/edible/recipe/response.proto", fileDescriptor_d319aa5d297fd1ed)
}

var fileDescriptor_d319aa5d297fd1ed = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0x2f, 0x4a, 0x4d, 0xce, 0x2c, 0x00,
	0x51, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x7a, 0x60, 0x59, 0x21, 0x31, 0x88, 0xac, 0x1e, 0x44,
	0x56, 0x0f, 0x26, 0xab, 0x24, 0xca, 0x25, 0x1c, 0x04, 0x16, 0x0a, 0x2e, 0xc9, 0x2f, 0x4a, 0x0d,
	0x82, 0x0a, 0x3b, 0xb1, 0x45, 0xb1, 0xa4, 0x16, 0x15, 0x24, 0x25, 0xb1, 0x81, 0x75, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe7, 0x31, 0x26, 0x64, 0x00, 0x00, 0x00,
}
