// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/menu/model.proto

package empb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The schema of the Food message.
type Food struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc6f52109f8a0be5, []int{0}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Food) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Food)(nil), "edible.menu.model.Food")
}

func init() { proto.RegisterFile("protos/edible/menu/model.proto", fileDescriptor_bc6f52109f8a0be5) }

var fileDescriptor_bc6f52109f8a0be5 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0xcf, 0x4d, 0xcd, 0x2b, 0xd5, 0xcf,
	0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x03, 0x4b, 0x08, 0x09, 0x42, 0x24, 0xf4, 0x40, 0x12, 0x7a, 0x60,
	0x09, 0x25, 0x1d, 0x2e, 0x16, 0xb7, 0xfc, 0xfc, 0x14, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92,
	0x9c, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0xc7, 0x89, 0x2d, 0x8a, 0x25, 0x35,
	0xb7, 0x20, 0x29, 0x89, 0x0d, 0x6c, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xec, 0x68, 0x06,
	0xd4, 0x71, 0x00, 0x00, 0x00,
}
