// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/menu/request.proto

package empb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request schema for calling List on menu.
type MenuListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuListRequest) Reset()         { *m = MenuListRequest{} }
func (m *MenuListRequest) String() string { return proto.CompactTextString(m) }
func (*MenuListRequest) ProtoMessage()    {}
func (*MenuListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9661809500364893, []int{0}
}

func (m *MenuListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuListRequest.Unmarshal(m, b)
}
func (m *MenuListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuListRequest.Marshal(b, m, deterministic)
}
func (m *MenuListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuListRequest.Merge(m, src)
}
func (m *MenuListRequest) XXX_Size() int {
	return xxx_messageInfo_MenuListRequest.Size(m)
}
func (m *MenuListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MenuListRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MenuListRequest)(nil), "edible.menu.request.MenuListRequest")
}

func init() { proto.RegisterFile("protos/edible/menu/request.proto", fileDescriptor_9661809500364893) }

var fileDescriptor_9661809500364893 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0xcf, 0x4d, 0xcd, 0x2b, 0xd5, 0x2f,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x03, 0x4b, 0x09, 0x09, 0x43, 0xa4, 0xf4, 0x40, 0x52,
	0x7a, 0x50, 0x29, 0x25, 0x41, 0x2e, 0x7e, 0xdf, 0xd4, 0xbc, 0x52, 0x9f, 0xcc, 0xe2, 0x92, 0x20,
	0x88, 0x90, 0x13, 0x5b, 0x14, 0x4b, 0x6a, 0x6e, 0x41, 0x52, 0x12, 0x1b, 0x58, 0x9b, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xea, 0x2f, 0xca, 0xe5, 0x5a, 0x00, 0x00, 0x00,
}
