// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/menu/response.proto

package empb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The response you get for calling List on menu.
type MenuListResponse struct {
	Foods                []*Food  `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuListResponse) Reset()         { *m = MenuListResponse{} }
func (m *MenuListResponse) String() string { return proto.CompactTextString(m) }
func (*MenuListResponse) ProtoMessage()    {}
func (*MenuListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59772eeb77311c00, []int{0}
}

func (m *MenuListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuListResponse.Unmarshal(m, b)
}
func (m *MenuListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuListResponse.Marshal(b, m, deterministic)
}
func (m *MenuListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuListResponse.Merge(m, src)
}
func (m *MenuListResponse) XXX_Size() int {
	return xxx_messageInfo_MenuListResponse.Size(m)
}
func (m *MenuListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MenuListResponse proto.InternalMessageInfo

func (m *MenuListResponse) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

func init() {
	proto.RegisterType((*MenuListResponse)(nil), "edible.menu.response.MenuListResponse")
}

func init() { proto.RegisterFile("protos/edible/menu/response.proto", fileDescriptor_59772eeb77311c00) }

var fileDescriptor_59772eeb77311c00 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0xcf, 0x4d, 0xcd, 0x2b, 0xd5, 0x2f,
	0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x03, 0xcb, 0x09, 0x89, 0x40, 0xe4, 0xf4, 0x40,
	0x72, 0x7a, 0x30, 0x39, 0x29, 0x39, 0x2c, 0x1a, 0x73, 0xf3, 0x53, 0x52, 0x73, 0x20, 0xba, 0x94,
	0x1c, 0xb9, 0x04, 0x7c, 0x53, 0xf3, 0x4a, 0x7d, 0x32, 0x8b, 0x4b, 0x82, 0xa0, 0x7a, 0x84, 0x74,
	0xb9, 0x58, 0xd3, 0xf2, 0xf3, 0x53, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xc4, 0xf5,
	0x90, 0x4d, 0x86, 0x68, 0x76, 0xcb, 0xcf, 0x4f, 0x09, 0x82, 0xa8, 0x72, 0x62, 0x8b, 0x62, 0x49,
	0xcd, 0x2d, 0x48, 0x4a, 0x62, 0x03, 0x9b, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xe6,
	0x1d, 0x81, 0xac, 0x00, 0x00, 0x00,
}
