// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/edible/inventory/response.proto

package eipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The response you get for calling Recycle on inventory.
type InventoryRecycleResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryRecycleResponse) Reset()         { *m = InventoryRecycleResponse{} }
func (m *InventoryRecycleResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryRecycleResponse) ProtoMessage()    {}
func (*InventoryRecycleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd717a5a5a65e1, []int{0}
}

func (m *InventoryRecycleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryRecycleResponse.Unmarshal(m, b)
}
func (m *InventoryRecycleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryRecycleResponse.Marshal(b, m, deterministic)
}
func (m *InventoryRecycleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryRecycleResponse.Merge(m, src)
}
func (m *InventoryRecycleResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryRecycleResponse.Size(m)
}
func (m *InventoryRecycleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryRecycleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryRecycleResponse proto.InternalMessageInfo

func (m *InventoryRecycleResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// The response you get for calling Use on inventory.
type InventoryUseResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryUseResponse) Reset()         { *m = InventoryUseResponse{} }
func (m *InventoryUseResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryUseResponse) ProtoMessage()    {}
func (*InventoryUseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd717a5a5a65e1, []int{1}
}

func (m *InventoryUseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryUseResponse.Unmarshal(m, b)
}
func (m *InventoryUseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryUseResponse.Marshal(b, m, deterministic)
}
func (m *InventoryUseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryUseResponse.Merge(m, src)
}
func (m *InventoryUseResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryUseResponse.Size(m)
}
func (m *InventoryUseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryUseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryUseResponse proto.InternalMessageInfo

func (m *InventoryUseResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// The response you get for calling Buy on inventory.
type InventoryBuyResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryBuyResponse) Reset()         { *m = InventoryBuyResponse{} }
func (m *InventoryBuyResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryBuyResponse) ProtoMessage()    {}
func (*InventoryBuyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd717a5a5a65e1, []int{2}
}

func (m *InventoryBuyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryBuyResponse.Unmarshal(m, b)
}
func (m *InventoryBuyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryBuyResponse.Marshal(b, m, deterministic)
}
func (m *InventoryBuyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryBuyResponse.Merge(m, src)
}
func (m *InventoryBuyResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryBuyResponse.Size(m)
}
func (m *InventoryBuyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryBuyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryBuyResponse proto.InternalMessageInfo

func (m *InventoryBuyResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*InventoryRecycleResponse)(nil), "edible.inventory.response.InventoryRecycleResponse")
	proto.RegisterType((*InventoryUseResponse)(nil), "edible.inventory.response.InventoryUseResponse")
	proto.RegisterType((*InventoryBuyResponse)(nil), "edible.inventory.response.InventoryBuyResponse")
}

func init() {
	proto.RegisterFile("protos/edible/inventory/response.proto", fileDescriptor_f0fd717a5a5a65e1)
}

var fileDescriptor_f0fd717a5a5a65e1 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xc9, 0x4c, 0xca, 0x49, 0xd5, 0xcf, 0xcc, 0x2b, 0x4b, 0xcd, 0x2b,
	0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x03, 0x2b, 0x10,
	0x92, 0x84, 0x28, 0xd0, 0x83, 0x2b, 0xd0, 0x83, 0x29, 0x50, 0x32, 0xe2, 0x92, 0xf0, 0x84, 0x89,
	0x06, 0xa5, 0x26, 0x57, 0x26, 0xe7, 0xa4, 0x06, 0x41, 0xe5, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x4b,
	0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0xa0, 0x3c, 0x25, 0x3d, 0x2e,
	0x11, 0xb8, 0x9e, 0xd0, 0x62, 0xd2, 0xd4, 0x3b, 0x95, 0x56, 0x12, 0x52, 0x9f, 0xc4, 0x06, 0x76,
	0xb5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x64, 0x0d, 0x19, 0x8d, 0xdf, 0x00, 0x00, 0x00,
}
