// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protos/edible/inventory/service.proto

package eipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// Unary
	Recycle(ctx context.Context, in *InventoryRecycleRequest, opts ...grpc.CallOption) (*InventoryRecycleResponse, error)
	Use(ctx context.Context, in *InventoryUseRequest, opts ...grpc.CallOption) (*InventoryUseResponse, error)
	Buy(ctx context.Context, in *InventoryBuyRequest, opts ...grpc.CallOption) (*InventoryBuyResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) Recycle(ctx context.Context, in *InventoryRecycleRequest, opts ...grpc.CallOption) (*InventoryRecycleResponse, error) {
	out := new(InventoryRecycleResponse)
	err := c.cc.Invoke(ctx, "/edible.inventory.service.InventoryService/Recycle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Use(ctx context.Context, in *InventoryUseRequest, opts ...grpc.CallOption) (*InventoryUseResponse, error) {
	out := new(InventoryUseResponse)
	err := c.cc.Invoke(ctx, "/edible.inventory.service.InventoryService/Use", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Buy(ctx context.Context, in *InventoryBuyRequest, opts ...grpc.CallOption) (*InventoryBuyResponse, error) {
	out := new(InventoryBuyResponse)
	err := c.cc.Invoke(ctx, "/edible.inventory.service.InventoryService/Buy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations should embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	// Unary
	Recycle(context.Context, *InventoryRecycleRequest) (*InventoryRecycleResponse, error)
	Use(context.Context, *InventoryUseRequest) (*InventoryUseResponse, error)
	Buy(context.Context, *InventoryBuyRequest) (*InventoryBuyResponse, error)
}

// UnimplementedInventoryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) Recycle(context.Context, *InventoryRecycleRequest) (*InventoryRecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recycle not implemented")
}
func (UnimplementedInventoryServiceServer) Use(context.Context, *InventoryUseRequest) (*InventoryUseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Use not implemented")
}
func (UnimplementedInventoryServiceServer) Buy(context.Context, *InventoryBuyRequest) (*InventoryBuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_Recycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryRecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Recycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edible.inventory.service.InventoryService/Recycle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Recycle(ctx, req.(*InventoryRecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Use_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryUseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Use(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edible.inventory.service.InventoryService/Use",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Use(ctx, req.(*InventoryUseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryBuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edible.inventory.service.InventoryService/Buy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Buy(ctx, req.(*InventoryBuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edible.inventory.service.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recycle",
			Handler:    _InventoryService_Recycle_Handler,
		},
		{
			MethodName: "Use",
			Handler:    _InventoryService_Use_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _InventoryService_Buy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/edible/inventory/service.proto",
}
